Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /favicon.ico
Not Found: /wp-includes/wlwmanifest.xml
Not Found: /xmlrpc.php
Not Found: /blog/wp-includes/wlwmanifest.xml
Not Found: /web/wp-includes/wlwmanifest.xml
Not Found: /wordpress/wp-includes/wlwmanifest.xml
Not Found: /website/wp-includes/wlwmanifest.xml
Not Found: /wp/wp-includes/wlwmanifest.xml
Not Found: /news/wp-includes/wlwmanifest.xml
Not Found: /2018/wp-includes/wlwmanifest.xml
Not Found: /2019/wp-includes/wlwmanifest.xml
Not Found: /shop/wp-includes/wlwmanifest.xml
Not Found: /wp1/wp-includes/wlwmanifest.xml
Not Found: /test/wp-includes/wlwmanifest.xml
Not Found: /media/wp-includes/wlwmanifest.xml
Not Found: /wp2/wp-includes/wlwmanifest.xml
Not Found: /site/wp-includes/wlwmanifest.xml
Not Found: /cms/wp-includes/wlwmanifest.xml
Not Found: /sito/wp-includes/wlwmanifest.xml
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/js/main.js
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/apple-touch-icon.png
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/js/main.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/logo.png
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/apple-touch-icon.png
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/apple-touch-icon.png
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2658][26792] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/favicon.png
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/img/apple-touch-icon.png
Not Found: /static/assets/img/apple-touch-icon.png
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /robots.txt
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /robots.txt
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online.zidni.id'. You may need to add 'www.faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online.zidni.id'. You may need to add 'www.faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online.zidni.id'. You may need to add 'www.faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online.zidni.id'. You may need to add 'www.faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /robots.txt
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /merchant/z/payment/
Not Found: /merchant/z/payment/
Not Found: /merchant/code
Not Found: /merchant/code
Not Found: /3ds1633693954432212
Not Found: /3ds1633693954432212
Not Found: /3ds.php
Not Found: /3ds.php
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /robots.txt
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /robots.txt
Not Found: /static/assets/img/logo.png
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /wp-includes/wlwmanifest.xml
Not Found: /xmlrpc.php
Not Found: /blog/wp-includes/wlwmanifest.xml
Not Found: /web/wp-includes/wlwmanifest.xml
Not Found: /wordpress/wp-includes/wlwmanifest.xml
Not Found: /website/wp-includes/wlwmanifest.xml
Not Found: /wp/wp-includes/wlwmanifest.xml
Not Found: /news/wp-includes/wlwmanifest.xml
Not Found: /2020/wp-includes/wlwmanifest.xml
Not Found: /2019/wp-includes/wlwmanifest.xml
Not Found: /shop/wp-includes/wlwmanifest.xml
Not Found: /wp1/wp-includes/wlwmanifest.xml
Not Found: /test/wp-includes/wlwmanifest.xml
Not Found: /wp2/wp-includes/wlwmanifest.xml
Not Found: /site/wp-includes/wlwmanifest.xml
Not Found: /cms/wp-includes/wlwmanifest.xml
Not Found: /sito/wp-includes/wlwmanifest.xml
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'faridsoftwareengineer.online.zidni.id'. You may need to add 'faridsoftwareengineer.online.zidni.id' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/favicon.png
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.faridsoftwareengineer.online'. You may need to add 'www.faridsoftwareengineer.online' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/features.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/vendor/fontawesome-free/css/all.min.css
Not Found: /static/assets/vendor/boxicons/css/boxicons.min.css
Not Found: /static/assets/vendor/glightbox/css/glightbox.min.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.css
Not Found: /static/assets/css/style.css
Not Found: /static/assets/img/about.jpg
Not Found: /static/assets/img/departments-1.jpg
Not Found: /static/assets/img/departments-2.jpg
Not Found: /static/assets/img/departments-3.jpg
Not Found: /static/assets/vendor/aos/aos.css
Not Found: /static/assets/vendor/bootstrap/css/bootstrap.min.css
Not Found: /static/assets/vendor/animate.css/animate.min.css
Not Found: /static/assets/img/logo.png
Not Found: /static/assets/vendor/bootstrap-icons/bootstrap-icons.css
Not Found: /static/assets/vendor/swiper/swiper-bundle.min.js
Not Found: /static/assets/js/main.js
Not Found: /static/assets/vendor/php-email-form/validate.js
Not Found: /static/assets/vendor/glightbox/js/glightbox.min.js
Not Found: /static/assets/vendor/purecounter/purecounter_vanilla.js
Not Found: /static/assets/vendor/aos/aos.js
Not Found: /static/assets/img/gallery/gallery-1.jpg
Not Found: /static/assets/img/testimonials/testimonials-1.jpg
Not Found: /static/assets/img/departments-4.jpg
Not Found: /static/assets/img/testimonials/testimonials-2.jpg
Not Found: /static/assets/img/gallery/gallery-2.jpg
Not Found: /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/assets/img/testimonials/testimonials-3.jpg
Not Found: /static/assets/img/gallery/gallery-8.jpg
Not Found: /static/assets/img/testimonials/testimonials-5.jpg
Not Found: /static/assets/img/testimonials/testimonials-4.jpg
Not Found: /static/assets/img/doctors/doctors-1.jpg
Not Found: /static/assets/img/doctors/doctors-2.jpg
Not Found: /static/assets/img/doctors/doctors-3.jpg
Not Found: /static/assets/img/doctors/doctors-4.jpg
Not Found: /static/assets/img/gallery/gallery-3.jpg
Not Found: /static/assets/img/gallery/gallery-6.jpg
Not Found: /static/assets/img/gallery/gallery-4.jpg
Not Found: /static/assets/img/gallery/gallery-7.jpg
Not Found: /static/assets/img/gallery/gallery-5.jpg
Not Found: /static/assets/img/slide/slide-2.jpg
Not Found: /static/assets/img/slide/slide-3.jpg
Not Found: /static/assets/img/slide/slide-1.jpg
Not Found: /static/assets/img/features.jpg
[ERROR] [UID:2658][16290] wsgiAppHandler pApp->start_response() return NULL.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined
[ERROR] [UID:2658][18749] wsgiAppHandler pApp->start_response() return NULL.
Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/views/debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 683, in resolve
    for pattern in self.url_patterns:
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/u8129117/virtualenv/public_html/faridsoftwareengineer.online/3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u8129117/public_html/faridsoftwareengineer.online/herb8terapi/herb8terapi/urls.py", line 28, in <module>
    if settings.DEBUG:
NameError: name 'settings' is not defined
